[package]
name = "emfind"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dict = "0.1.5"
konst = "0.3.4"
unicode-segmentation = "1.10.0"
